# Generated by Django 2.0 on 2018-06-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ask',
            new_name='chat',
        ),
    ]
