# Generated by Django 2.0 on 2018-06-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180628_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
