# Generated by Django 2.0 on 2018-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='department name required', max_length=120),
        ),
    ]
